"""Publication figure style for the thesis supplement.

One place for every colour and rcParam the figure scripts use, so the whole
supplement reads as a single system.

Colour rules followed here (all machine-validated, see module docstring notes):

* **Score (-1..5) is ordinal magnitude**, so it takes a single-hue blue ramp,
  light -> dark, never a rainbow and never eight categorical hues.  The 6- and
  7-step ramps below were generated by OKLab interpolation between the blue
  ramp's step-250 and step-700 anchors and pass the ordinal gate (monotone
  lightness, adjacent OKLCH dL >= 0.06, light end >= 2:1 against the surface,
  single hue).
* **Nominal groups** (feature family, epoch, feature set) take fixed
  categorical slots in a fixed order - blue, orange, aqua.  Those three pass
  the all-pairs CVD and normal-vision floors in light mode.
* **Magnitude heatmaps** use the one-hue blue sequential ramp; **signed
  quantities** (log ratios, correlations, differences) use a blue<->red
  diverging ramp with a neutral grey midpoint, so zero reads as "nothing".
"""

from __future__ import annotations

import matplotlib as mpl
import numpy as np
from matplotlib.colors import LinearSegmentedColormap

# --- chrome & ink ----------------------------------------------------------
SURFACE = "#fcfcfb"
PRIMARY = "#0b0b0b"
SECONDARY = "#52514e"
MUTED = "#898781"
GRID = "#e1e0d9"
AXIS = "#c3c2b7"

# --- ordinal score ramps (one hue, light -> dark) --------------------------
SCORE_RAMP_6 = ["#86b6ef", "#6d9bd3", "#5480b8", "#3c679e", "#254e84", "#0d366b"]
SCORE_RAMP_7 = ["#86b6ef", "#719fd8", "#5c89c1", "#4874ab", "#345f95", "#214a80", "#0d366b"]

# --- categorical slots (fixed order, never cycled) -------------------------
CAT = ["#2a78d6", "#eb6834", "#1baf7a"]

# --- sequential / diverging ramps ------------------------------------------
_SEQ_STEPS = ["#cde2fb", "#9ec5f4", "#5598e7", "#2a78d6", "#1c5cab", "#104281", "#0d366b"]
SEQ_CMAP = LinearSegmentedColormap.from_list("blue_seq", _SEQ_STEPS)
DIV_CMAP = LinearSegmentedColormap.from_list(
    "blue_red_div", ["#0d366b", "#2a78d6", "#86b6ef", "#f0efec", "#f0a09f", "#e34948", "#8f2323"]
)

# --- odor-window annotation -------------------------------------------------
ODOR_SHADE = "#f0efec"


def score_colors(levels) -> dict:
    """Map an ordered list of score levels onto the matching ordinal ramp."""
    levels = list(levels)
    ramp = SCORE_RAMP_6 if len(levels) <= 6 else SCORE_RAMP_7
    if len(levels) != len(ramp):
        idx = np.linspace(0, len(ramp) - 1, len(levels)).round().astype(int)
        ramp = [ramp[i] for i in idx]
    return dict(zip(levels, ramp))


def apply_style() -> None:
    """Install the supplement's rcParams. Call once at script start."""
    mpl.rcParams.update({
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
        "savefig.facecolor": SURFACE,
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans", "Helvetica", "Arial"],
        "font.size": 8.0,
        "axes.titlesize": 9.0,
        "axes.titleweight": "bold",
        "axes.titlelocation": "left",
        "axes.titlepad": 6.0,
        "axes.labelsize": 8.0,
        "axes.labelcolor": SECONDARY,
        "axes.edgecolor": AXIS,
        "axes.linewidth": 0.6,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "axes.axisbelow": True,
        "grid.color": GRID,
        "grid.linewidth": 0.5,
        "grid.linestyle": "-",
        "xtick.labelsize": 7.0,
        "ytick.labelsize": 7.0,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "xtick.major.width": 0.6,
        "ytick.major.width": 0.6,
        "xtick.major.size": 2.5,
        "ytick.major.size": 2.5,
        "legend.fontsize": 7.0,
        "legend.frameon": False,
        "legend.handlelength": 1.4,
        "legend.labelspacing": 0.35,
        "legend.columnspacing": 1.2,
        "lines.linewidth": 1.3,
        "lines.solid_capstyle": "round",
        "text.color": PRIMARY,
        "figure.dpi": 110,
        "savefig.dpi": 400,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.03,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def tidy(ax, *, grid_axis: str = "y") -> None:
    """Recessive chrome: hairline grid on one axis only, no top/right spines."""
    ax.grid(False)
    if grid_axis in ("x", "both"):
        ax.xaxis.grid(True, color=GRID, linewidth=0.5)
    if grid_axis in ("y", "both"):
        ax.yaxis.grid(True, color=GRID, linewidth=0.5)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(AXIS)
        ax.spines[side].set_linewidth(0.6)


def mark_odor_window(ax, on_s: float, off_s: float, *, label: bool = False) -> None:
    """Shade the odor-on window; a solid hairline pair, never dashes."""
    ax.axvspan(on_s, off_s, color=ODOR_SHADE, zorder=0, linewidth=0)
    for x in (on_s, off_s):
        ax.axvline(x, color=AXIS, linewidth=0.6, zorder=1)
    if label:
        ax.text((on_s + off_s) / 2, 0.97, "odor on", transform=ax.get_xaxis_transform(),
                ha="center", va="top", fontsize=7, color=MUTED)


def ink_on(hex_color: str) -> str:
    """Ink that stays legible on top of ``hex_color`` — primary on light, surface on dark."""
    r, g, b = (int(hex_color[i:i + 2], 16) / 255 for i in (1, 3, 5))
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    return PRIMARY if lum > 0.55 else SURFACE


def cell_grid(ax, n_rows: int, n_cols: int) -> None:
    """Hairline surface gaps between heatmap cells — a gap, never a border."""
    ax.set_xticks(np.arange(-0.5, n_cols, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, n_rows, 1), minor=True)
    ax.grid(which="minor", color=SURFACE, linewidth=1.2)
    ax.tick_params(which="minor", length=0)


def colorbar(fig, im, ax, label: str, **kw):
    """A recessive colorbar: no outline, small label, tight to its axes."""
    cb = fig.colorbar(im, ax=ax, **{"fraction": 0.040, "pad": 0.02, **kw})
    cb.set_label(label, fontsize=7)
    cb.ax.tick_params(labelsize=6.5, length=2)
    cb.outline.set_visible(False)
    return cb


def save(fig, outdir, stem: str) -> None:
    """Write vector PDF (for the thesis) and 400 dpi PNG (for quick viewing)."""
    from pathlib import Path

    outdir = Path(outdir)
    (outdir / "pdf").mkdir(parents=True, exist_ok=True)
    (outdir / "png").mkdir(parents=True, exist_ok=True)
    fig.savefig(outdir / "pdf" / f"{stem}.pdf")
    fig.savefig(outdir / "png" / f"{stem}.png")
    print(f"  saved {stem}.pdf / .png")
