fps: 40.0
pre_s: 2.0
post_s: 2.0
lag_ms: 250
n_components: 5
threshold_k: 4.0
smoothing:
  enable: true
  savgol_window_ms: 151
  savgol_poly: 3
frequency:
  enable: false
  bands_hz:
    - [0.5, 5.0]
clustering:
  method: gmm
  n_components: 2
